blognotes/blognotes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myblog.urls')),
    # The login and logout Views, which are inbuilt CBVs
    path('accounts/login/',
         views.LoginView.as_view(template_name='registration/login.html'),
         name='login'),
    # Go to homepage after logging-out
    path('account/logout/', views.LogoutView.as_view(),
         name='logout', kwargs={'next_page': '/'}),
]

blognotes/myblog/urls.py
from django.urls import path

# Importing views
from myblog import views

app_name = 'myblog'

urlpatterns = [
    # ## Class Based Views
    # homepage, about Page, Create Post views
    path('', views.PostListView.as_view(), name='post_list'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('post/new/', views.CreatePostView.as_view(), name='post_new'),
    # # Views that require primary key input
    # Detail view, Update View and Delete view
    path('post/<int:pk>/', views.PostDetailView.as_view(),
         name='post_detail'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(),
         name='post_edit'),
    path('post/<int:pk>/remove/', views.PostDeleteView.as_view(),
         name='post_remove'),
    # Draft List View
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),

    # ## Function Based Views
    path('post/<int:pk>/comment/', views.add_comment_to_post,
         name='add_comment_to_post'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('comment/<int:pk>/approve/',
         views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove,
         name='comment_remove'),
]

blognotes/myblog/models.py
from django.db import models

# To add current time to posts based on UTC in settings.py
from django.utils import timezone

from django.urls import reverse

# Model to store each blog post,


class Post(models.Model):
    '''
    model class to store the Post
    fields: author, title, text, creation date, publication date
    '''
    # Only authorized(superuser) users can add a new post
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(null=True, blank=True)

    def publish(self):
        '''
        method in model 'Post', a post is only added to the model
        after publish, with published 'date & time'
        '''
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        '''
        Any one can comment on a post, but all of them not gonna get approved,
        This method filters out unapproved(approved_comment = False) comments
        from Comment class, So that only approved(approved_comment = True)
        comments save to the model 'Post'
        '''
        # This 'Post' model and the following 'Comment' model related with a
        # ForeignKey, Each comment is attached to a 'Post', the name
        # 'comments' is the 'related_name' in the relation
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        '''
        After Someone creates a post, the user need to be taken to the posts
        detailed view page('post_detail'-# name in urls.py),
        Detailed view always needs the primary key(pk) to display/identify the
        post 'self.pk' represents return to the detailed view of same post
        after creating
        '''
        return reverse("myblog:post_detail", kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


# Model to store comments

class Comment(models.Model):
    '''
    The Comment model class is attached to Post--ForeignKey,
    Anyone can put a comment to a post but it need to get approved, an
    approved_comment attribute so added extra to this Comment class
    '''
    # 'myblog.Post' refers to myblog-->models.py-->Post model,
    post = models.ForeignKey(
        'myblog.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=256)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        '''
        To approve a comment and save to db
        '''
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        '''
        return to the list view(ie the homepage) after commenting on
        a post, the comments needs approval to display
        '''
        return reverse("myblog:post_list")

    def __str__(self):
        return self.text

blognotes/myblog/forms.py
from django import forms

# import the models
from myblog.models import Post, Comment

# Form to create post


class PostForm(forms.ModelForm):
    '''
    Model form from model=Post
    '''
    class Meta():
        model = Post
        fields = ('author', 'title', 'text')

        # To get custom styling to forms, adding html field attributes for
        # the<p> classnames refers to the external css library used
        # 'textinputclass' and 'postcontent are custom classes they are need
        # to specify here cz, which are added with django templating in forms.
        widgets = {
            # Bootstrap & medium js fetching classes
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(
                attrs={'class': 'editable medium-editor-textarea postcontent'}
            )
        }

# Form to comment a post


class CommentForm(forms.ModelForm):
    '''
    Model form for model=Comment
    '''
    class Meta():
        model = Comment
        fields = ('author', 'text')

        # Similer kind of widgets as PostForm, no 'postcontent' custom class
        widgets = {
            'author': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(
                attrs={'class': 'editable medium-editor-textarea'}
            )
        }

blognotes/myblog/views.py
# Import FBV classes
from django.shortcuts import render, get_object_or_404, redirect
# Import timezone
from django.utils import timezone
# Importing reverse and reverse_lazy
from django.urls import reverse, reverse_lazy
# Import the CBVs classes
from django.views.generic import (TemplateView, ListView,
                                  DetailView, CreateView,
                                  UpdateView, DeleteView)
# Importing the LoginRequiredMixin for CBV and the @login_required decorator
# for fun. based views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Import the models and forms
from myblog.models import Post, Comment
from myblog.forms import PostForm, CommentForm

# Create your views here.


class AboutView(TemplateView):
    """
    View for the About page, links the about.html template
    """
    template_name = 'about.html'

# ########################################
# ######## THE CRUD CBVs ############
# ########################################

# CRUD --Retrieval of Information


class PostListView(ListView):
    """
    Views the homepage, list view of posts, post_list.html
    """
    model = Post

    def get_queryset(self):
        """
        Using Django ORM(Object Relational Mapping) with DB, this querysets
        allows perform SQLqueries in a 'pythonish' way,
        which just means from model 'Post' grab all 'objects'(ie posts)
        'filter' it out based on 'published_date'
        attribute less than or equal to(lte) the current time(timezone.now()),
        'order_by' descending order of ("-")
        published date.
        lller SQL query
        'SELECT * FROM Post WHERE published_date <= timezone.now()'
        """
        return Post.objects.filter(published_date__lte=timezone.now()
                                   ).order_by('-published_date')


class PostDetailView(DetailView):
    """
    Detail view of post, post_detail.html
    """
    model = Post

# CRUD --Creating


class CreatePostView(LoginRequiredMixin, CreateView):
    """
    view of formpage to write up the post, similar to 'login_required'
    decorator CBV's got mixins which inherits to the classes provides the same
    functionality that a user must be logged in, to add a post
    """
    # If this view(CreatePostView) is requested, without a login, it must
    # revert to the login page
    login_url = '/login/'
    redirect_field_name = 'myblog/post_detail.html'

    form_class = PostForm
    model = Post

# CRUD --Updating


class PostUpdateView(LoginRequiredMixin, UpdateView):
    """
    The PostUpdateView is same as CreatePostview, but in here there's only
    updation of the existing one happens
    """
    login_url = '/login/'
    redirect_field_name = 'myblog/post_detail.html'

    form_class = PostForm
    model = Post

# CRUD --Deleting


class PostDeleteView(LoginRequiredMixin, DeleteView):
    """
    This view Deletes the post from the DB,(DeleteView-manages that)
    if the post is deleted, it takes user back to 'Post list view'
    """
    model = Post
    success_url = reverse_lazy('myblog:post_list')

# ########The CRUD CBV's COMPLETED  ###################
# ######################################################

# Draft View class


class DraftListView(LoginRequiredMixin, ListView):
    """
    Drafts are unpublished blogs, This view is to show them,
    this also need login to see
    """
    login_url = '/login/'
    redirect_field_name = 'myblog/post_list.html'

    model = Post

    def get_queryset(self):
        """
        queryset to find which posts are not published
        by looking up if the 'published_date' == null and order descending by
        created date
        """
        return Post.objects.filter(published_date__isnull=True
                                   ).order_by('-create_date')

# ############ Function Based Views ###################

# To Publish Post


@login_required
def post_publish(request, pk):
    """
    To publish the post, using the method 'publish' in model class 'Post'
    :param request:
    :param pk:
    :return: to the post_detail view of published post
    """
    # Grab the object or return a 404(not found) error
    post = get_object_or_404(Post, pk=pk)
    # call the 'publish' method in 'Post', which adds the current date&time
    # and saves the post to Post model
    post.publish()
    return redirect('myblog:post_detail', pk=post.pk)


# Add comment to post view

@login_required
def add_comment_to_post(request, pk):
    """
    To add a comment when a 'request' with primary key('pk') of post given,
    :param request:
    :param pk:
    :return: the html tag 'form' and the form is created based on logic
    """
    # Grab the object or return a 404(not found) error
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        # If the form filled and request submitted
        # get the content to form
        form = CommentForm(request.POST)
        if form.is_valid():
            # checking the form valid or not,
            # if valid save to DB
            comment = form.save(commit=False)
            # post in Comment model foreignkey relation, attach comment to
            # this post
            comment.post = post
            comment.save()
            # after saving redirect to current post_detail page
            return redirect('myblog:post_detail', pk=post.pk)
    else:
        # the form is not posted stay on comment form
        form = CommentForm()
    # render out the html based on 'form' template tagging in
    # 'comment_form.html'
    return render(request, 'myblog/comment_form.html', {'form': form})

# Approve comment view


@login_required()
def comment_approve(request, pk):
    """
    View to approve comment, using the 'approve' method in Comment model,
    ie, when 'approve' method called it sets the boolean value 'True'
    :param request:
    :param pk:
    :return: to the post_detail view of current post
    """
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('myblog:post_detail', pk=comment.post.pk)

# Remove comment view


@login_required()
def comment_remove(request, pk):
    """
    View to Delete a comment, using the 'delete' method in Comment model
    ( native in 'models.Model'), an extra variable required to store the key
    value of comment(ie key of post) to delete
    :param request:
    :param pk:
    :return: to the post_detail view of current post
    """
    comment = get_object_or_404(Comment, pk=pk)
    # variable to store pk
    post_pk = comment.post.pk
    comment.delete()
    return redirect('myblog:post_detail', pk=post_pk)

blognotes/myblog/templates/myblog/abc.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <div class="container">
      <div class="jumbotron">
          <h1>Hello mayavi</h1>

      </div>

  </div>

  </body>
</html>
<!-- {% extends "myblog/base.html" %}

{% block body_block %}

<style>
  body{
        background-image: url("/static/images/about_background.jpg");
        background-size: cover;
        background-repeat: no-repeat;
        background-position:center;
        background-attachment: fixed;
    }
</style>
{% endblock %} -->

blognotes/myblog/templates/myblog/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
    <!-- Bootstrap local css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Font Awsome   -->
    <script src="https://kit.fontawesome.com/57433fac3b.js" crossorigin="anonymous"></script>

    <!-- Custom css -->
    <link rel="stylesheet" href="{% static 'css/myblog.css' %}">

    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&family=Righteous&display=swap" rel="stylesheet">
    <!-- font-family: 'Righteous', cursive; font-family: (handwriting)'Pacifico', cursive; -->
  </head>
  <body class="about-body">
    <nav class="navbar navbar-expand-lg navbar-dark aboutnav">

        <!-- Setting the brand(main letter on left) here ""-->
        <a class="navbar-brand bigbrand" href="{% url 'myblog:post_list' %}">
          <img id="logo_brand2" src="{% static 'images/blog_logo2.png' %}" class="d-inline-block align-top" alt="Na NAA, Error!">
        Blognotes
        </a>

        <!-- Adding the Hamburger button -->
        <button class="navbar-toggler ml-auto custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Dropdown and adding the Home link, ul > li item > content(anchor tag)-->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'myblog:about' %}">About<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#">Github<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#">Linkedin<span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto navbar-right">
            {% if user.is_authenticated %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'myblog:post_new' %}">New Post</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'myblog:post_draft_list' %}">Drafts</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link">Welcome: {{user.username}}</a>
              </li>
            {% else %}
              <!-- Glyphicon use -->
              <li class="nav-item active">
                <a class="nav-link navbar-right loginbutton" href="{% url 'login' %}"><i class="far fa-address-card"></i></a>
              </li>
            {% endif %}
          </ul>

        </div>
      </nav>
      <div class="container about">
          <h1><u>About me</u></h1>
          <p>Akshay Chandran, email: akshaych203@gmail.com</p>
          <p class="loader thanks"><strong>Thanks for checking out!</strong></p>
          <h5>Resources Taken From:</h5>
          <p><a href="https://github.com/yabwe/medium-editor">Medium Style Editor: yabwe(github)</a></p>
          <p><a href="https://codepen.io/thapliyalshivam/pen/dvgXVO">Color Changing Effect: Shivam Thapliyal(codepen)</a></p>
          <p>And Thanks to <a href="https://www.udemy.com/user/joseportilla/">Jose Portila</a> for all the guidence.</p>
     </div>
  </body>
  <!-- Necessory js and bootstrap files -->
      <script
      src="https://code.jquery.com/jquery-3.4.1.js"
      integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
      crossorigin="anonymous"></script>
      <!-- local bootstrap js files -->
      <script src="{% static 'js/bootstrap.js' %}"></script>
      <!-- Medium editor js file -->
      <script src="{% static 'js/medium-editor.js' %}"></script>
</html>

blognotes/myblog/templates/myblog/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title></title>
    <!-- Bootstrap local css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Font Awsome   -->
    <script src="https://kit.fontawesome.com/57433fac3b.js" crossorigin="anonymous"></script>

    <!-- Medium editor js file -->
    <script src="{% static 'js/medium-editor.js' %}"></script>
    <!-- medium style editor and its theme -->
    <link rel="stylesheet" href="{% static 'css/medium-editor.css' %}">
    <link rel="stylesheet" href="{% static 'css/themes/beagle.css' %}">

    <!-- Custom css -->
    <link rel="stylesheet" href="{% static 'css/myblog.css' %}">

    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@600&family=Merriweather:wght@300&family=Righteous&display=swap" rel="stylesheet">
    <!-- font-family: 'Righteous', cursive; font-family: font-family: 'Merriweather', serif; font-family: 'Josefin Sans', sans-serif; -->
</head>
<body class="body-back">
    <!-- Setting the navbar and its style -->
    <nav class="navbar navbar-expand-lg navbar-custom techfont">

      <!-- Setting the brand(main letter on left) here ""-->
      <a class="navbar-brand bigbrand" href="{% url 'myblog:post_list' %}">
        <img id="logo_brand" src="{% static 'images/blog_logo.png' %}" class="d-inline-block align-top" alt="Na NAA, Error!">
      Blognotes
      </a>

      <!-- Adding the Hamburger button -->
      <button class="navbar-toggler ml-auto custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Dropdown and adding the Home link, ul > li item > content(anchor tag)-->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto loader">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myblog:about' %}">About<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="https://github.com/Akshay-ch-dj/Blognotes-Django-simple-blog-project">Github<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#">Linkedin<span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto navbar-right loader">
          {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'myblog:post_new' %}">New Post</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'myblog:post_draft_list' %}">Drafts</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" id="welcome">Welcome: {{user.username}}</a>
            </li>

          {% else %}
            <!-- fontawsome icon use -->
            <li class="nav-item active">
              <a class="nav-link navbar-right loginbutton" href="{% url 'login' %}"><i class="far fa-address-card"></i></a>
            </li>
          {% endif %}
        </ul>

      </div>
    </nav>

    <!-- CONTENT BLOCK -->
    <div class="content container">
      <!-- row, collapsing things -->
      <div class="row">
        <div class="col-xs-6 col-lg-10">
          <!-- col-md-8 col-sm-8 -->
          <div class="blog-posts">
              {% block body_block %}
                <!-- Anything inside will be protected  -->
              {% endblock %}
          </div>
        </div>
      </div>
    </div>
</body>
<!--Compailed JS Bootstrap-->
<!-- Necessory js and bootstrap files -->
    <script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
    <!-- local bootstrap js files -->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <!-- Medium editor js file -->
    <script src="{% static 'js/medium-editor.js' %}"></script>
    </html>

blognotes/myblog/templates/myblog/comment_form.html
{% extends "myblog/base.html" %}

{% block body_block %}
  <h1>New Comment</h1>
  <form class="post_form" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="save btn btn-primary">Post Comment</button>
  </form>
  <!-- Adding medium editor capabilities -->
  <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

blognotes/myblog/templates/myblog/post_confirm_delete.html
{% extends "myblog/base.html" %}

<!-- When clickn 'delete' success url -->
{% block body_block %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ object }}?</p>
    <input type="submit" class="btn btn-danger" value="Confirm">
  </form>

{% endblock %}

blognotes/myblog/templates/myblog/post_detail.html
{% extends "myblog/base.html" %}

<!-- The detailed post view with comments template -->
{% block body_block %}
<!-- The template with major content in this project-->

  <!-- The 'loder' is the color changing css class, displays post title as h1-->
  <h1 class="posttitle loader">{{post.title}}</h1>
  {% if post.published_date %}
  <!--if the post is published -->
    <div class="date postdate">
      {{ post.published_date }}
    </div>
  {% else %}
  <!-- if not published -->
    <p>Created on: {{ post.create_date|date:"D M Y" }}</p>
    <!-- show a button which takes to the publish url -->
    <a class="btn btn-primary" href="{% url 'myblog:post_publish' pk=post.pk %}">Publish</a>
  {% endif %}
  <!-- the 'safe' prevents displaing html tags(from medium-js, like <b>Bold text<b>) -->
  <!-- safe transforms that html looks to real looks -->
  <!-- 'linebreaksbr',a line break in html converted to real world line break -->
  <p class="postcontent">{{post.text|safe|linebreaksbr}}</p>

  {% if user.is_authenticated %}
  <!-- if user is authenticated, need two buttons 'edit' and 'remove' the post -->
    <a class="btn btn-primary" href="{% url 'myblog:post_edit' pk=post.pk %}">
      <i class="fas fa-edit"></i>
    </a>
    <a class="btn btn-primary" href="{% url 'myblog:post_remove' pk=post.pk %}">
      <i class="fas fa-eraser"></i>
    </a>
  {% endif %}

  <!-- horizontal break -->
  <hr>
  <!-- Add comment button -->
  <a class="btn btn-primary btn-comment" href="{% url 'myblog:add_comment_to_post' pk=post.pk %}">Add Comment</a>

  <div class="container">
    {% for comment in post.comments.all %}
      <br>
        {% if user.is_authenticated or comment.approved_comment %}
          {{comment.create_date}}
          {% if not comment.approved_comment %}
          <!-- need two buttons one to approve the comment & one to remove it -->
            <a class="btn btn-primary" href="{% url 'myblog:comment_approve' pk=comment.pk %}">
              <i class="fas fa-check"></i>
            </a>
            <a class="btn btn-primary" href="{% url 'myblog:comment_remove' pk=comment.pk %}">
              <i class="fas fa-times"></i>
            </a>
          {% endif %}

          <!-- The comment text filtered -->
          <p>{{comment.text|safe|linebreaks}}</p>
          <p>Posted By: {{comment.author}}</p>

        {% endif %}
        <!-- If comment section is empty -->
        {% empty %}
        <p>No Comments</p>
    {% endfor %}

  </div>
{% endblock %}

blognotes/myblog/templates/myblog/post_draft_list.html
{% extends "myblog/base.html" %}

<!-- Drft view of un published posts -->
{% block body_block %}
  <!-- post_list preffered ?????, what is posts??-->
  {% for post in posts %}
    <div class="post">
      <p class="date">created: {{ post.create_date|date:'d-m-Y' }}</p>
      <h1><a href="{% url 'myblog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
      <!-- filter 'truncatechars' helps in formatting(optional) -->
      <!-- <p>{{post.text|truncatechars:200}}</p> -->
    </div>
  {% endfor %}
{% endblock %}

blognotes/myblog/templates/myblog/post_form.html
{% extends "myblog/base.html" %}

{% block body_block %}
  <h1>New Post</h1>
  <form class="post-form" method="POST">
    {% csrf_token %}
    <!-- The widget class added in the form can be used for individual styling -->
    {{form.as_p}}
    <!-- bootstrap styled save button -->
    <button type="submit" class="save btn btn-primary loader">Save</button>
  </form>
  <!-- instantiate a new MediumEditor object, required for the js to work -->
  <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

blognotes/myblog/templates/myblog/post_list.html
{% extends "myblog/base.html" %}

<!-- List view that lists out the whole posts -->
{% block body_block %}
<div class="centerstage">
  {% for post in post_list %}
  <!-- The 'post_list' is returned by ListView CBVs, containes all post object models-->
    <div class="post">
      <!--Display all the posts in 'h1 tag' when clicked go to its detailed view with pk-->
      <h1><a href="{% url 'myblog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
      <div class="date">
        <!-- below heading display published_date as 'p' with a date template filters -->
      {% if post.published_date %}
        <p>Published on: {{ post.published_date|date:"D M Y" }}</p>
      {% else %}
        <p>Created on: {{ post.create_date|date:"D M Y" }}</p>
      {% endif %}
      </div>
      <!-- Displayes no. of comments below if clicked go back to post detail where the comments are displayed -->
      <a href="{% url 'myblog:post_detail' pk=post.pk %}">Comments: {{post.approve_comments.count}}</a>
    </div>
  {% endfor %}
</div>
{% endblock %}